<?php 
/**
 * @file
 * A module that displays data about Jira tickets
 */

  /**
   * Implements hook_help
   * 
   * Displays help and module information
   * 
   */
   function jira_analysis_help($path, $arg) {
   	switch($path) {
		case "admin/help#jira_analysis": {
			$returnVal = '<h3>' . t('About') . '</h3>'; 
			$returnVal .= '<p>' . t('Displays data about Jira tickets') . '</p>';
			return $returnVal;
			break;
		}
   	}
   } 


 /**
  * Implements hook_permission().
  */
  function jira_analysis_permission() {
  	return array(
		'administer Jira Analysis' => array(
			'title' => t('Administer Jira Analysis'),
			'description' => t('Perform administrative tasks on Jira Analysis functionality'),
			),
	);
  }
 
 /**
  * Implements hook_menu().
  */
  function jira_analysis_menu() {
  	$items = array();
	/*
	// Admin configuration group.
	$items['admin/config/jira_analysis'] = array(
	'title' => 'Jira Analysis',
	'description' => 'Administer Jira Analysis',
	'access arguments' => array('Administer Jira Analysis'),
	);*/
	
	//Admin configuration - Settings.
	$items['admin/config/jira_analysis/settings'] = array(
	'title' => 'Jira Analysis Settings',
	'description' => 'Manage Jira Analysis settings and configuration',
	'access arguments' => array('Administer Jira Analysis'),
	'page callback' => 'drupal_get_form',
	'page arguments' => array('jira_analysis_admin_settings_form'),
	'type' => MENU_NORMAL_ITEM,
	);
	
	
	return $items;
  }
 
 /**
  * Implements hook_form().
  */
  function jira_analysis_admin_settings_form($node, &$form_state) {
  	$form = array();
	
	$form['overview'] = array(
	'#markup' => t('This interface allows administrators to manage general Jira Analysis Settings'),
	'#prefix' => '<p>',
	'#suffix' => '</p>',
	);
	/*
	$form['jira_analysis_credential_fieldset'] = array(
		'#title' => t('Jira Credentials'),
		'#type' => 'fieldset',
	);*/
	
	//$form['jira_analysis_credential_fieldset']
	$form['jira_analysis_default_URL'] = array(
		'#title' => t('URL'),
		'#description' => t('Jira REST URL eg "http://yourJiraInstallation.com/jira/rest/api/2/". You must include "/jira/rest/api/2/".'),
		'#type' => 'textfield',
		'#default_value' => variable_get('jira_analysis_default_URL', ''),
	);
	
	//$form['jira_analysis_credential_fieldset']
	$form['jira_analysis_default_user_name'] = array(
		'#title' => t('User Name'),
		'#description' => t(''),
		'#type' => 'textfield',
		'#default_value' => variable_get('jira_analysis_default_user_name', ''),
		'#required' => TRUE,
	);
	
	//$form['jira_analysis_credential_fieldset']
	$form['jira_analysis_default_password'] = array(
		'#title' => t('Password'),
		'#description' => t(''),
		'#type' => 'password',
		'#default_value' => variable_get('jira_analysis_default_password',''),
		'#required' => TRUE,
	);
	
  //create options array
  $statusList = array(
  	array(
		"description" => "The issue is open and ready for the assignee to start work on it.",
		"name" => "Open",
		"id" => 1
	),
	array(
		"description" => "",
		"name" => "Pre-Slated",
		"id" => 10023
	),	
	array(
		"description" => "The issue is awaiting work by a developer.",
		"name" => "Slated",
		"id" => 10000
	),
	array(
		"description" => "Work has begun on the issue.",
		"name" => "Development in Progress",
		"id" => 10001
	),
	array(
		"description" => "The issue is being reviewed by a stakeholder.",
		"name" => "Stakeholder Review in Progress",
		"id" => 10029
	),
	array(
		"description" => "This issue is waiting to have code reviewed by another developer.",
		"name" => "Queued for Code Review",
		"id" => 10016
	),
	array(
		"description" => "The issue is having code reviewed by a developer.",
		"name" => "Code Review in Progress",
		"id" => 10017
	),
	array(
		"description" => "The issue is awaiting staging.",
		"name" => "Queued for Staging QA",
		"id" => 10002
	),
	array(
		"description" => "The issue is staged for QA review.",
		"name" => "Staged for QA",
		"id" => 10003
	),
	array(
		"description" => "",
		"name" => "Ready for Release",
		"id" => 10027
	),
	array(
		"description" => "A resolution has been taken, and it is awaiting final verification in production.",
		"name" => "Newly Released",
		"id" => 5
	),
	array(
		"description" => "The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.",
		"name" => "Closed",
		"id" => 6
	),
	array(
		"description" => "",
		"name" => "Backlog",
		"id" => 10020
	),

  );

	

  $header = array(
    'name' => t('Status Name'),
    'description' => t('Description'),
  );
  
  
  $form['jira_analysis_statuses'] = array(
    '#type' => 'tableselect',
    '#header' => $header,
    '#options' => $statusList,
    '#empty' => t('No statuses found'),
  );
	
	

	
	/*$form['submit'] = array(
	'#type' => 'submit',
	'#value' => t('Save'),
	);*/
	
	return system_settings_form($form);
	
	//return $form;
  }
 
 /**
  * Validates jira admin settings.
  */
  function jira_analysis_admin_settings_form_validate($form, &$form_state) {
  	dpm($form_state);
	/*$ch = curl_init($form_state['values']['jira_analysis_default_URL'].'status');
	curl_setopt($ch, CURLOPT_USERPWD, $form_state['values']['jira_analysis_default_user_name'].':'.$form_state['values']['jira_analysis_default_password']);
	curl_setopt($ch, CURLOPT_POST, FALSE);
	curl_setopt($ch, CURLOPT_HTTPGET, TRUE);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
	curl_setopt($ch, CURLOPT_HEADER, TRUE);
	
	$resp = curl_exec($ch);
	$respCode = curl_getinfo($ch,CURLINFO_HTTP_CODE);
	if ($respCode != 200) {
		form_set_error('jira_analysis_credential_fieldset', t('Validation failed, please check your URL and credentials and re-submit ('.$respCode.')'));
	}
	curl_close($ch);
	*/
/*
	$ch = curl_init('http://ticketing.whitehouse.gov/rest/api/2/status');
	curl_setopt($ch, CURLOPT_USERPWD, 'mvogelgesang:L@crosse0');
	curl_setopt($ch, CURLOPT_POST, FALSE);
	curl_setopt($ch, CURLOPT_HTTPGET, TRUE);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
	curl_setopt($ch, CURLOPT_HEADER, TRUE);
	
	$resp = curl_exec($ch);
	$respCode = curl_getinfo($ch,CURLINFO_HTTP_CODE);
	if ($respCode != 200) {
		form_set_error('jira_analysis_credential_fieldset', t('Validation failed, please check your URL and credentials and re-submit ('.$respCode.')'));
	}
	curl_close($ch);
 * */
  }
 
 /**
  * Process a validated jira admin setting submission
  */
  function jira_analysis_admin_settings_form_submit($form, &$form_state) {
	//Rebuild the form.
	$form_state['rebuild'] = TRUE;
	
	// Save jira setting variables
	variable_set('jira_analysis_default_URL', $form_state['values']['jira_analysis_default_URL']);
	variable_set('jira_analysis_default_user_name', $form_state['values']['jira_analysis_default_user_name']);
  	variable_set('jira_analysis_default_password', $form_state['values']['jira_analysis_default_password']);
	//variable_set('jira_analysis_default_statuses', $form_state['values']['jira_analysis_statuses']);
	//variable_set('jira_analysis_default_status_list', $form_state['values']['jira_analysis_default_status_list']);
	
	//Nofity User
	drupal_set_message(t('Jira Analysis settings saved'));
  } 